request-yo-racks/web

src/my-app.html, src/my-view1.html, src/ryr-specify-coordinates.html, src/ryr-suggestion-list.html, src/shared-styles.html
Description
-----------
Implement a new page layout.
This layout is based on the data the the user is expected to input. The steps are layout out in a logical way.
Manually.
Checklist:
----------
=> Layout 0.1.0

package.json, src/my-view1.html, src/ryr-email-templatizer.html, src/ryr-suggestion-list.html
Description
-----------
The list containing the business names now implements selecting an item.
When an item is selected, the application queries the API to request
detailed information about the place, and transfer the result to the
templatizer component in order to start generating the email instantly.
The user should not have to add information manually.
Manually in the browser.
Checklist:
----------
=> Grid to api

.gitignore, Makefile, bower.json, src/my-view1.html, src/ryr-specify-coordinates.html
Description
-----------
* Move GoogleMaps into the location component
* Try to find a way to hide the Google Developer API key
* Get a better organize code base
* Display GoogleMaps
Manually
Checklist:
----------
=> Reorganize code

.gitignore, Dockerfile, Dockerfile.dev, Makefile, charts/values.minikube.yaml, docker/nginx/conf.d/default.conf, docker/nginx/nginx.conf, docker/nginx/proxy.conf, src/ryr-specify-coordinates.html, src/ryr-suggestion-list.html
Description
-----------
Adds the ability to easily deploy the project to a Kubernetes cluster.
Kubernetes is the way to orchestrate container deployments, therefore
adding the Kubernetes support to this project is the logical path to
follow.
Manually
- Infrastructure
Checklist:
----------
=> Kubernetize the project

Dockerfile, Makefile, charts/values.minikube.yaml
Description
-----------
Creates a multi-stage `Dockerfile` to build an ES5 version of the
project and then serving it using Nginx.
Also creates a `Dockerfile.dev` to serve the project using the
`polymer-cli` with the live-reload option. This should be useful in the
feature to develop locally and test the project in real time on
Minikube
Drive-by:
* Fix the service ports.
Needed to serve the project on Minikube.
Manually
Checklist:
----------
-  [] I have written unit …
=> Improve Dockerfile

.dockerignore, Dockerfile, Makefile
Description
-----------
* Fix/Clean up the Makefile
* Add a .dockerignore file
Being able to deploy the web application.
Manually
Checklist:
----------
=> Fix the deploy process

.github/PULL_REQUEST_TEMPLATE.md, src/ryr-email-templatizer.html, src/ryr-preview.html, src/ryr-specify-coordinates.html
Description
-----------
Fixes invalid syntax in the web components:
* for passing the GoogleMaps API key to the component
* in the documentation
Removing the errors during the build phase.
Manually.
Checklist:
----------
=> Fix invalid syntax

src/my-view1.html, src/ryr-location.html, src/ryr-suggestion-list.html
Description
-----------
Adds a more user friendly location component.
Drive-by:
* Make the marker move
* Fix api endpoint for populating the list
Make the application demoable.
Manually.
Checklist:
----------
=> Add a location-component

LICENSE.rst
Add license.rst.
Description
-----------
Add MIT license to projects.
The project didn't have the required license.
- Documentation
Checklist:
----------
-  [x] I have updated the documentation accordingly.
=> Add MIT License

.circleci/config.yml, .github/CONTRIBUTING.rst, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, Makefile, src/ryr-location.html, src/ryr-specify-coordinates.html, wct.conf.json
Description
-----------
Adds the ability to run the CI tasks of this project via CircleCI.
The Web Component Tester was configured to run Chrome and Firefox
headless.
Being able to test and ensure the a certain code quality before merging code.
Locally using the `Makefile` and on CircleCI.
Checklist:
----------
-  [X] I have written unit tests
Fixes: https://github.com/request-yo-racks/web/issues/29
=> Add CircleCI support

src/my-view1.html
Description
-----------
Moves copy clipboard to the right.
Better user experience
Screenshots:
------------
Before:
After:
Visual change
=> Float clipboard to the right

.circleci/config.yml
Description
-----------
Running WCT with different browsers.
Running WCT against different web browsers.
Manually.
Checklist:
----------
Fixes: https://github.com/request-yo-racks/web/<issue_number>
=> Uses upstream Selenium images to run WCT

.github/PULL_REQUEST_TEMPLATE.md, src/ryr-suggestion-list.html
Description
-----------
Ensures the text color of the suggestion list is black, to contrast with
the white background.
Being able to reads the text in the list.
Manually.
Screenshots:
------------
Checklist:
----------
Fixes request-yo-racks/web#51
=> Change the text color of the suggestion list.

.circleci/config.yml, .dockerignore, Dockerfile, Makefile
Description
-----------
It happens that the configuration sometime need to be initialized
of the application setup.
Drive-by:
* Use the Makefile to build the Dockerfile
Simplify the setup and build process.
Manually.
Checklist:
----------
=> Create target to initialize the configuration

src/my-app.html, src/my-view1.html, src/ryr-location.html, src/ryr-preview.html, src/shared-styles.html
Description
-----------
The "Get started" part in the "How it works?" section needed to be made
more engaging.
Drive-bys:
* Simplify the CSS
* Move common CSS selectors to the shared styles
* Use more composition instead of specific styles
Make the instructions more engaging.
Manually.
Checklist:
----------
Fixes request-yo-racks/web#52
=> Style "Get started"

src/my-view1.html, src/ryr-preview.html
Added color style to preview element
Fixes request-yo-racks/web#53
=> Added color style for preview element.

src/my-view1.html
Description
-----------
Writes a clear set of instructions to guide the user to sending his bike
rack request to the city of Austin.
Guide the users to complete the process.
Manually and via CI.
Screenshots:
------------
Mobile version:
Desktop version:
Checklist:
----------
Fixes request-yo-racks/web#33
=> Write email instructions

Dockerfile, Makefile, charts/values.prod.yaml, docker/nginx/conf.d/default.conf
Description
-----------
Updates the `Makefile` to allow developers to easily deploy the web app
to production.
Drive-by:
* Build as ES6
Fix the errors that were seen in production.
In a minikube environment.
Checklist:
----------
=> Add Makefile target to deploy to production

charts/values.prod.yaml, package-lock.json, package.json, src/my-app.html
Description
-----------
Screenshots:
------------
- Documentation
Checklist:
----------
Fixes request-yo-racks/web#<issue_number>
=> Adds TLS support.

.github/CONTRIBUTING.md
- Documentation
Description
-----------
Have clean and consistent documentation.
Checklist:
----------
-  [X] I have updated the documentation accordingly
=> Fix repo used in contributing.md

Makefile
Description
-----------
Helm was using the last Kubernetes context used, which could lead to
dramatic problems like wiping out production my mistake.
Prevent deployment mistakes.
Deploying a local development environment.
Checklist:
----------
Fixes request-yo-racks/web#105
=> Specify Kubernetes context explicitly with Helm

src/my-app.html
Description
-----------
There was a scrolling issue on the site causing 2 scrollbars to appear
as well as preventing us to take screenshot of the full site.
Being able to take full screenshot of the site.
Manually.
Checklist:
----------
=> Fix scrolling issue

images/logos/ryr_logo.svg
Add SVG logo for without the text.
Fixes request-yo-racks/web#93
- Added SVG logo.
Description
-----------
- Fixed inbalanced logo.
- Exported to SVG file.
=> Add SVG logo

bower.json, src/my-app.html, src/my-view1.html, src/shared-styles.html
Description
-----------
This patch updates the header and the footer to match the v2 design, as
well as ensuring that the interface stays responsive.
The app shell CSS was simplify to make sure it its maintenance will be
easy.
When switching to mobile mode, the menu is replaced by a drawer which contains the same items.
Desktop mode looks like this:
Mobile mode looks like this:
Footer looks like this:
Fulfill the v2 design.
Manually.
Checklist:
----------
-  [] I have updated the …
=> Update header and footer

src/my-view1.html
Description
-----------
Ensures the height of the preview component extends to make any amount
of text fit into it.
Make sure that the mobile version, or even the desktop version with long
text, is not broken.
Manually injecting a long text into the preview component.
Checklist:
----------
Fixes request-yo-racks/web#94
=> Fix the height issue of the preview component

src/my-view1.html
Description
-----------
The CSS for the warning box is now simpler and clearer. Using `display:
flex` makes it easier to position the elements and make the interface
responsive.
Checklist:
----------
=> Update the warning box

src/my-view1.html, src/shared-styles.html
Description
-----------
The sections colors, icons and font sizes have been updated the match the
v2 design.
Checklist:
----------
=> Update section colors, icons and font sizes

src/my-view1.html
Description
-----------
Makes some adjustments based on the comments.
Checklist:
----------
=> Make some adjustments to the main page

src/my-view1.html
Description
-----------
Limits the width of the view to 1024px and remove the margin for
viewports smaller than this.
Improve the appearance for larger viewports.
Checklist:
----------
=> Limit view width

.mergify.yml, src/ryr-suggestion-list.html
Description
-----------
The `/place` endpoint is not a `POST` endpoint, therefore the request
from the client has to be adjusted.
Checklist:
----------
=> Fix place detail request

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md
- Documentation
Description
-----------
The PR template had a bunch of sections that were most of the time
ignored by the contributors. 
In order to simplify the templates, these sections were turned into
comments, leaving the possibility for the contributor to be guided
to provide answers to them.
Checklist
---------
-  [X] I have updated the documentation accordingly
-  [ ] I have written unit tests
=> Simplify PR template

package-lock.json, package.json, pages/index.js
Description
-----------
Adds the support for Font Awesome via the react-fontawesome package.
Checklist
---------
=> Add support for Font Awesome

.mergify.yml, components/ryr-how-it-works.js, package-lock.json, pages/_document.js, pages/index.js, server.js
Description
-----------
Adds a component explaining how the app works.
Checklist
---------
Fixes request-yo-racks/web#147
=> Add how-it-works component

components/ryr-footer.js, components/ryr-how-it-works.js, pages/index.js
Description
-----------
Adds the RYR banner picture right under the navbar.
Drive-by:
* Place the components in the appropriate document sections.
Checklist
---------
Fixes request-yo-racks/web#158
=> Add banner picture

components/ryr-section-connector.js, pages/index.js
Description
-----------
Creates the connector component, taking the filling and the background
colors as parameters. Also prepares the sections with placeholders.
Checklist
---------
Fixes request-yo-racks/web#160
=> Create a connector component

.circleci/config.yml, .gitignore, .mergify.yml, components/ryr-location-selector.js, components/ryr-popup-item.js, components/ryr-popup.js, next.config.js, package-lock.json, package.json, pages/index.js, server.js
Description
-----------
Add some components to:
1. Display the map using mapbox-gl
2. Query the API with the location clicked on the map and display the
results of the search in the result component, on top of the map.
Drive-by:
* Fix dynamic import in tests
Checklist
---------
Fixes request-yo-racks/web#152
=> Implement MapBox-GL map

package-lock.json, package.json
- Security advisory
Description
-----------
Update `npm-run-all` dev dependency in order to remove `flatmap-stream`
from the `package.json.lock` file.
`flatmap-stream` was considered malicious and removed from the NPM
registry.
Ref: https://www.npmjs.com/advisories/737
Checklist
---------
=> Remediate security advisories

components/ryr-email.js, components/ryr-location-selector.js, components/ryr-popup.js, package-lock.json, package.json, pages/_app.js, pages/index.js, redux/store.js
Description
-----------
Implements a redux store to allow components to communicate together.
Especially in a first time the location component must be able to
communicate with the email template component to render the message
based on the information collected on the internet.
Checklist
---------
=> Implement Redux store

components/ryr-location-selector.js, pages/index.js
Description
-----------
Read the Mapbox token from environment variables to prevent committing
it with the code => also better practices.
Checklist
---------
=> Read the Mapbox Token from env var

components/ryr-popup.js
Description
-----------
When the map loads, it is not aware of the first selected item until the
user actually clicks it. This patch makes sure that the first location
loaded is used to populate the email.
Checklist
---------
=> Select the first location on load

components/ryr-location-selector.js, package-lock.json, package.json, redux/saga.js, redux/store.js
Description
-----------
As we are now using redux, we can start using `redux-sagas` to manage
asynchronous tasks.
This patch implement the first saga which consists in fetching the list
of place summaries to display on the map.
Checklist
---------
=> Implement sagas to manage async tasks

components/ryr-location-selector.js, components/ryr-popup.js, components/ryr-section-connector.js, pages/index.js
Description
-----------
The section connector was somewhat buggy so I replaced it with another
one. The visual is as expected, but the component will eventually need
to be removed and the code moved to the section itself (created with
emotion.js).
Checklist
---------
=> Fix the section connector

components/ryr-email.js, components/ryr-popup.js, redux/saga.js, redux/store.js
Description
-----------
Implements a new saga to fetch the details of the selected place.
The email message was adjusted to process the object containing the
detailed information about the place.
Checklist
---------
=> Fetch place details

package-lock.json, package.json, pages/index.js
Description
-----------
Uses the emotion library to style and the index page.
* Add emotion packages
* Update configuration in `package.json`
Checklist
---------
=> Use emotion for index.js

components/ryr-how-it-works.js
Description
-----------
Styles the `How-It-Works` component using the emotion library.
Checklist
---------
=> Use emotion to style How-It-Works

components/ryr-how-it-works.js, components/ryr-popup-item.js, pages/index.js
Description
-----------
Styles the `PopUpItem` component using the emotion library.
Checklist
---------
=> Use emotion to style PopUpItem

components/ryr-how-it-works.js, package-lock.json, package.json, pages/index.js
Description
-----------
Using `facepaint` from `emotion`, we can define dynamic styles based on
specific breakpoints, allowing us to make the UI responsive.
Checklist
---------
=> Make the UI responsive
